### ISSUE TITLE
Customisation.

### ISSUE THREAD

**Issue by begin-theadventure** [a-bravo/threads-for-youtube#17]
1) Colors.
Preset themes (Default, YouTube dark/light) or/and the ability to change to any color.
2) Default tab.
Option to change the default tab to Reddit posts/comments or YouTube comments.

**Comment by a-bravo** [comment]
> 1. Colors.
>    Preset themes (Default, YouTube dark/light) or/and the ability to change to any color.

The color of the extension changes with YouTube's appearance (try changing from YouTube dark mode / light mode to see how it changes)

**Comment by a-bravo** [comment]
> 2\. Default tab.
>     Option to change the default tab to Reddit posts/comments or YouTube comments.

This already exists in the extension's options/preferences. Go to your browser's extension/add-on management page and you should be able to find the link to this extension's options/preferences

<details>
<summary>Screenshots</summary>
  
Firefox:
![Screen Shot 2022-12-27 at 10 12 29 PM](https://user-images.githubusercontent.com/49041010/209766525-24eee928-50b0-4cb8-8f24-43a6a96b33b4.png)

Chrome:
![Screen Shot 2022-12-27 at 10 12 51 PM](https://user-images.githubusercontent.com/49041010/209766568-8dd3ca11-4095-45e2-83a5-e8b86954a3cd.png)
 
</details>

**Comment by begin-theadventure** [comment]
> This already exists in the extension's options/preferences. Go to your browser's extension/add-on management page and you should be able to find the link to this extension's options/preferences

That's great! I didn't know that this extension has preferences, because the icon doesn't display on the bar.

As for the colors, I mainly mean the red tabs (color). I'd like to change them to a dark color.

**Comment by a-bravo** [comment]
A little late, but you can now customize the accent color in the settings page (as of v0.13.0)

**Comment by begin-theadventure** [comment]
Great!
