### ISSUE TITLE
Text stays black on dark mode

### ISSUE THREAD

**Issue by Bluberius** [a-bravo/threads-for-youtube#23]
At some point, the text stopped beeing displayed white when dark mode is activated. Now the text blends in the background and is not readable:
![2023-09-02 12_13_24](https://github.com/a-bravo/threads-for-youtube/assets/15158778/2fbe80bf-4a67-4fc3-96e0-95a111ba89e3)

**Comment by a-bravo** [comment]
This is fixed in the latest update (v0.12.0)
